---
title: Promise
date: 2020-05-23 14:10:00
tags:
categories:
- JavaScript
---

使用回调表达程序异步和管理并发的两个主要缺陷：缺乏顺序性和可信任性。


## 什么是 Promise
### 未来值
未来值的一个重要特性：它可能成功，也可能失败。

为了统一处理现在和将来，我们把它们都变成了将来，即所有的操作都成了异步的。

```javascript
function add(xPromise, yPromise) {
    return Promise.all([xPromise, yPromise]).then(function(values) {
        return values[0] + values[1];
    })
}

add(fetchX(), fetchY()).then(function(sum) {
    console.log(sum);
})
```
在 add(..) 内部，`Promise.all([..])` 调用创建了一个 promise，这个 promise 等待 promiseX 和 promiseY 的决议。链式调用 .then(..) 创建了另外一个 promise，这个 promise 由 `return values[0] + values[1]` 这一行立即决议，因此，链 add(..) 调用实际上操作的是返回的第二个 promise。

Promise 的决议结果可能是拒绝而不是完成。拒绝值和完成的 Promise 不一样：完成值总是编程给出的，而拒绝值，通常称为拒绝原因(rejection reason)，可能是程序逻辑直接设置的，也可能是从运行异常隐式得出的值。

从外部看，由于 Promise 封装了依赖于时间的状态 —— 等待底层值的完成或拒绝，所以 Promise 本身是与时间无关的。因此，Promise 可以按照可预测的方式组合，而不用关心时序或底层的结果。

另外，一旦 Promise 决议，它就永远保持在这个状态。此时它就成为了不变值(immutable value)，可以根据需求多次查看。

Promise 是一种封装和组合未来值的易于复用的机制。


### 完成事件
单独的 Promise 展示了未来值的特性。但是也可以从另一个角度看待 Promise 的决议：一种在异步任务中作为两个或更多步骤的流程控制机制，时序上的 this-then-that。

在典型的 JavaScript 风格，如果需要侦听某个通知，会用到事件。因此，可以把对通知的需求组织为对 foo(..) 发出一个完成事件的侦听。

使用回调的话，通知就是任务 (foo(..)) 调用的回调，而使用 Promise 的话，侦听来自 foo(..) 的事件，然后在得到通知的时候，根据情况继续。

```javascript
function foo(x) {
    // 开始做点可能耗时的工作
    // 构造一个 listener 事件通知处理对象来返回
    return listener;
}

var evt = foo(42);

evt.on("completion", function() {
    // 可以进行下一步
})

evt.on("failure", function() {
    // 出错了
})
```
foo(..) 显式创建并返回了一个事件订阅对象，调用代码得到这个对象，并在其上注册了两个事件处理函数。

相对于面向回调的代码，这里的反转是显而易见的，没有把回调传给 foo(..)，而是返回一个名为 evt 的事件注册对象，由它来接受回调。对回调模式的反转可称为反控制反转，把控制权还给调用代码。

一个很重要的好处是，可以把这个事件侦听对象提供给代码中的多个独立部分，在 foo(..) 完成的时候，它们都可以独立得到通知，以执行下一步。

从本质上说，evt 对象就是分离的关注点之间一个中立的第三方协商机制。

事件侦听对象 evt 就是 Promise 的一个模拟。我们侦听的 Promise 决议事件严格来说并不算是事件，尽管它们实现目标的行为确实很像事件。

```javascript
function foo(x) {
    // 可能做一些耗时的工作

    // 构造并返回一个 promise
    return new Promise(function(resolve, reject) {
        // 最终调用 resolve 或 reject
        // 这是 promise 的决议回调
    })
}

var p = foo(42);

bar(p);

baz(p);
```
`new Promise(function(..){ .. })` 传入的函数会立即执行，不会像 then(..) 中的回调一样异步延迟。

Promise 决议除了作为未来值查看，也可以作为一种流程控制信号。

Promise(一旦决议)一直保持其决议结果(完成或拒绝)不变，可以按照需要多次查看。


## 具有 then 方法的鸭子模型
在 Promise 领域，一个重要的细节是如何确定某个值是不是真正的 Promise。

识别 Promise (或者行为类似于 Promise 的东西)就是定义某种称为 thenable 的东西，将其定义为任何具有 then(..) 方法的对象和函数，我们认为，任何这样的值就是 Promise 一致的 thenable。

根据一个值的形态(具有哪些属性)对这个值的类型作出一些假定，这种类型检查(type check)一般用鸭子类型(dyck typing)来表示。

对 thenable 值的鸭子类型检测：
```javascript
if (p != null && 
    (
        typeof p === "object" || 
        typeof p === "function"
    ) &&
    typeof p.then === "function"
) {
    // 假定这是一个 thenable
} else {
    // 不是 thenable
}
```
如果你试图使用恰好有 then(..) 函数的一个对象或函数值完成一个 Promise，但并不希望它被当作 Promise 或 thenable，那就麻烦了，因为它会被自动识别为 thenable，并被按照特定的规则处理。

即使你并没有意识到这个值有 then(..) 函数：
```javascript
var o = { then: function(){} };

// 让 v [[Prototype]] 链接到 o
var v = Object.create(o);

v.someStuff = "cooool";
v.otherStuff = "foooool";

v.hasOwnProperty("then"); // false
```
v 看起来根本不像 Promise 或 thenable，它只是具有一些属性的简单对象，如果像其他对象一样发送这个值，但是 thenable 鸭子类型检测会把 v 认作一个 thenable。

甚至不需要是直接有意支持的：
```javascript
Object.prototype.then = function(){};
Array.prototype.then = function(){};

var o1 = { key: 'vvv' };
var a1 = [ 'aa', 'bb' ];
```
如果有任何其他代码无意或恶意地给 Object.prototype、Array.prototype 或任何其他原生原型添加 then(..)，那么无法控制也无法预测。并且如何指定的是不调用其参数作为回调的函数，那么如果 Promise 决议到这样的值，就会永远挂住！

标准决定劫持之前未保留的属性名 then，这意味着所有值，不管是过去的、现存的还是未来的，都不能拥有 then(..) 函数，不管是有意还是无意的，否则这个值在 Promise 系统中就会被误认为是一个 thenable，这可能导致难以追踪的 bug。

注意⚠️：如果 thenable 鸭子类型误把不是 Promise 的东西识别为 Promise，那可能就是有害的。


## Promise 的信任问题
Promise 模式构建的最重要的特性：信任。

### 调用过早
根据定义，即使是立即完成的 Promise 也无法被同步观察到。
```javascript
function foo() {
    return new Promise(function(resolve)) {
        resolve(42);
    }
}
```
对一个 Promise 调用 then(..) 的时候，即使这个 Promise 已经决议，提供给 then(..) 的回调也总会被异步调用。

### 调用过晚
Promise 创建对象调用 resolve(..) 或 reject(..) 时，这个 Promise 的 then(..) 注册的观察回调就会被自动调度。可以确信，这些被调度的回调在下一个异步事件点上一定会被触发。

同步查看是不可能的，所以一个同步任务链无法以这种方式运行来实现按照预期有效延迟另一个回调的发生。也就是说，一个 Promise 决议后，这个 Promise 上所有的通过 then(..) 注册的回调都会在下一个异步时机点上依次被立即调用。这些回调中的任意一个都无法影响或延误对其他回调的调用。

```javascript
p.then(function() {
    p.then(function() {
        console.log('C');
    })
    console.log('A');
})
p.then(function() {
    console.log('B');
})

// A B C
```

两个独立的 Promise 上链接的回调的相对顺序无法可靠预测：
```javascript
var p3 = new Promise(function(resolve, reject) {
    resolve("B");
})

var p1 = new Promise(function(resolve, reject) {
    resolve(p3);
})

var p2 = new Promise(function(resolve, reject) {
    resolve("A");
})

p1.then(function(v) {
    console.log(v);
})
p2.then(function(v) {
    console.log(v);
})

// A B
```
p1 不是立即值，而是用另一个 promise p3 决议，后者本身决议为值 B。规定的行为是把 p3 展开到 p1，但是是异步地展开，所以在异步任务队列中，p1 的回调安排在 p2 回调之后。

### 回调未调用
首先，没有任何东西能阻止 Promise 向你通知它的决议(如果它决议了的话)。如果对一个 Promise 注册了一个完成回调和一个拒绝回调，那么 Promise 在决议时总是会调用其中的一个。

但是，如果 Promise 本身永远不被决议呢？即使这样，可以使用一种称为竞态的高级抽象机制：
```javascript
// 用于超时一个 Promise 的工具
function timeoutPromise(delay) {
    return new Promise(function(resolve, reject) {
        setTimeout(function() {
            reject("Timeout");
        }, delay);
    })
}

// 设置 foo() 超时
Promise.race([
    foo(), 
    timeoutPromise(3000)
]).then(function() {
    // foo(..) 及时完成
}, function(err) {
    // foo() 被拒绝, 或者只是没能按时完成
    // 查看 err 确定是哪种情况
})
```
可以保证 foo() 有一个输出信号，防止其永久挂住程序。

### 调用次数过少或过多
根据定义，回调被调用的正确次数应该是 1。过少的情况是调用 0 次，和前面的未被调用是同一种情况。

Promise 的定义方式使得它只能被决议一次。如果出于某种原因，Promise 创建代码试图调用 resolve(..) 或 reject(..) 多次，或者试图两者都调用，那么这个 Promise 将只会接受第一次决议，并默默地忽略任何后续调用。

由于 Promise 只能被决议一次，所以任何通过 then(..) 注册的每个回调就只会被调用一次。

如果把同一个回调注册了不止一次，那么它被调用的次数就会和注册次数相同。

### 未能传递参数/环境值
Promise 至多只能有一个决议值(完成或拒绝)。

如果没有用任何值显式决议，那么这个值就是 undefined。不管这个值是什么，无论当前还是未来，它都会被传递给所有注册的(且适当的完成或拒绝)回调。

如果使用多个参数调用 resolve(..) 或者 reject(..)，第一个参数之后的所有参数都会被默默忽略。

如果要传递多个值，就必须要把它们封装在单个值中传递，比如通过一个数组或对象。

对环境来说，JavaScript 中的函数总是保持其定义所在的作用域的闭包，所以它们可以访问所提供的环境状态。

### 吞掉错误或异常
如果拒绝一个 Promise 并出一个出错消息，这个值就会被传递给拒绝回调。

如果在 Promise 的创建过程中或在查看其决议结果过程中的任何时间点上出现了一个 JavaScript 异常错误，比如一个 TypeError 或 ReferenceError，那这个异常就会被捕捉，并且会使这个 Promise 被拒绝。

```javascript
var p = new Promise(function(resolve, reject) {
    foo.bar();
    resolve(42);
})
p.then(
    function fulfilled() {
        //
    },
    function rejected(err) {
        console.log(err)
        // err 将会是一个 TypeError 异常对象来自 foo.bar() 行
    }
);

// ReferenceError: foo is not defined
```
Promise 甚至把 JavaScript 异常也变成了异步行为。

但是，如果 Promise 完成后在查看结果时(then(..) 注册的回调中)出现了 JavaScript 异常：
```javascript
var p = new Promise(function(resolve, reject) {
    resolve(42);
})
p.then(
    function fulfilled(data) {
        foo.bar();
        console.log(msg);
    },
    function rejected(err) {
        console.log(err)
    }
);

// Promise {<rejected>: ReferenceError: foo is not defined
//     at fulfilled (<anonymous>:6:9)}
// __proto__: Promise
// [[PromiseStatus]]: "rejected"
// [[PromiseValue]]: ReferenceError: foo is not defined at fulfilled (<anonymous>:6:9)
```
p.then(..) 调用本身返回了另外一个 promise，正式这个 promise 将会因 TypeError 异常而被拒绝。

为什么它不是简单地调用我们定义的错误处理函数呢？如果这样的话就违背了 Promise 的一条基本原则：即 Promise 一旦决议就不可再变。p 已经完成为值 42，所以之后查看 p 的决议时，并不能因为出错就把 p 再变为一个拒绝。

### 是可信任的 Promise 吗
Promise 并没有完全摆脱回调，它只是改变了传递回调的位置。我们并不是把回调传递给 foo(..)，而是从 foo(..) 得到某个东西，然后把回调传给这个东西。

如果向 Promise.resolve(..) 传递一个非 Promise、非 thenable 的立即值，就会得到一个用这个值填充的 promise。下面这种情况中，promise p1 和 promise p2 的行为是完全一致的：
```javascript
var p1 = new Promise(function(resolve, reject) {
    resolve(42);
})
var p2 = Promise.resolve(42);
```

而如果向 Promise.resolve(..) 传递一个真正的 Promise，就只会返回同一个 promise：
```javascript
var p1 = Promise.resolve(42);

var p2 = Promise.resolve(p1);

console.log(p1 === p2); // true
```

如果向 Promise.resolve(..) 传递一个非 Promise 的  thenable 值，前者就会试图展开这个值，而且展开过程会持续到提取出一个具体的非类 Promise 的最终值：
```javascript
var p = {
    then: function(cb) {
        cb(42);
    }
}

p.then(
    function fulfilled(val) {
        console.log(val);
    },
    function rejected(err) {
        console.log(err)
    }
)

// 42
```
这个 p 是一个 thenable，但并不是一个真正的 Promise。
```javascript
var p = {
    then: function(cb, errcb) {
        cb(42);
        errcb("evil");
    }
}

p.then(
    function fulfilled(val) {
        console.log(val);
    },
    function rejected(err) {
        console.log(err)
    }
)

// 42
// evil
```
这个 p 是一个 thenable，但是其行为和 promise 并不完全一致。不管哪种情况，它都是不可信的。

尽管如此，我们还是都可以把这些版本的 p 传给 Promise.resolve(..)，然后得到期望中的规范化后的安全结果：
```javascript
Promise.resolve(p)
.then(
    function fulfilled(val) {
        console.log(val);
    },
    function rejected(err) {
        console.log(err)
    }
)

// 42
```
Promise.resolve(..) 可以接受任何 thenable，将其解封为它的非 thenable 值。从 Promise.resolve(..) 得到的是一个真正的 Promise，是一个可以信任的值。

对于用 Promise.resolve(..) 为所有函数的返回值(不管是不是 thenable)都封装一层，这样做很容易把函数调用规范为定义良好的异步任务。

### 建立信任
Promise 这种模式通过可信任的语义把回调作为参数传递，使得这种行为更可靠更合理。通过把回调的控制反转反转回来，我们把控制权放在了一个可信任的系统中，这种系统的设计目的就是为了使异步编码更清晰。


## 链式流
可以把多个 Promise 连接到一起以表示一系列异步步骤。

这种方式可以实现的关键在于以下两个 Promise 固有行为特性：
- 每次对 Promise 调用 then(..)，它都会创建并返回一个新的 Promise，我们可以将其链接起来；
- 不管从 then(..) 调用的完成回调(第一个参数)返回的值是什么，它都会被自动设置为被链接 Promise(第一点中的)的完成。

```javascript
var p = Promise.resolve(21);

var p2 = p.then(function(v) {
    console.log(v); // 21
    return v*2;
})

p2.then(function(v) {
    console.log(v); // 42
})
```
如果必须创建临时变量，还是有些麻烦的：
```javascript
var p = Promise.resolve(21);

p.
then(function(v) {
    console.log(v); // 21
    return v*2;
})
.then(function(v) {
    console.log(v); // 42
})
```
现在第一个 then(..) 就是异步序列中的第一步，第二个 then(..) 就是第二部，这可以任意扩展下去。只要保持把先前的 then(..) 连到自动创建的每一个 Promise 上即可。

使 Promise 序列真正能够在每一步有异步能力的关键是，Promise.resolve(..) 会直接返回接收到的真正 Promise，或展开接收到的 thenable 值，并在持续展开 thenable 的同时递归地前进。

从完成(或拒绝)处理函数返回 thenable 或者 Promise 的时候也会发生同样的展开：
```javascript
var p = Promise.resolve(21);

p.then(function(v) {
    console.log(v);

    return new Promise(function(resolve, reject) {
        resolve(v * 2);
    })
}).then(function(v) {
    console.log(v);
})

// 21
// 42
```
虽然我们把 42 封装到了返回的 promise 中，但它仍然会被展开并最终成为链接的 promise 的决议，因此第二个 then(..) 得到的仍然是 42。如果向封装的 promise 引入异步，一切都仍然会同样工作：
```javascript
var p = Promise.resolve(21);

p.then(function(v) {
    console.log(v);

    return new Promise(function(resolve, reject) {
        setTimeout(function() {
            resolve(v * 2);
        }, 1000);
    })
}).then(function(v) {
    console.log(v);
})

// 21
// 42
```
现在我们可以构建这样一个序列：不管我们想要多少个异步步骤，每一步都能够根据需要等待下一步。

如果不显式返回一个值，就会隐式返回 undefined，并且这些 promise 仍然会以同样的方式链接在一起，这样，每个 Promise 的决议就成了继续下一步骤的信号。

```javascript
function delay(time) {
    return new Promise(function(resolve, reject) {
        setTimeout(resolve, time);
    })
}

delay(100)
.then(function STEP2() {
    console.log("step 2 (after 100ms)");
    return delay(200);
})
.then(function STEP3() {
    console.log("step 3 (after another 200ms)");
})
.then(function STEP4() {
    console.log("step 4 (next job)");
    return delay(50);
})
.then(function STEP5() {
    console.log("step 50 (after another 50ms)");
})
```
构建 Promise 链不仅是一个表达多步异步序列的流程控制，还是一个从一个步骤到下一步骤传递消息的消息通道。

如果这个 Promise 链中的某个步骤出错了怎么办？错误和异常是基于每个 Promise 的，这意味着可能在链的任意位置捕捉到这样的错误，而这个捕捉动作在某种程度上就相当于在这一位置将整条链重置回了正常运作。

当从完成处理函数返回一个 promise 时，它会被展开并有可能延迟下一个步骤。从拒绝处理函数返回的 promise 也是如此。

调用 then(..) 时的完成处理函数或拒绝处理函数如果抛出异常，都会导致链中的下一个 promise 因为这个异常而立即被拒绝。

如果调用 promise 的 then(..)，并且只传入一个完成处理函数，就会生成一个默认的拒绝处理函数：
```javascript
var p = new Promise(function(resolve, reject) {
    reject("Oops");
})
var p2 = p.then(
    function fulfilled() {
        // 永远不会到这里
    },
    // 假定的拒绝处理函数，如果省略或者传入非函数值
    // function(err) {
    //     throw err;
    // }
)
```
默认拒绝处理函数只是把错误重新抛出，最终会使得 p2 用同样的错误理由拒绝。从本质上说，这使得错误可以继续沿着 Promise 链传播下去，直到遇到显式定义的拒绝处理函数。

如果没有给 then(..) 传递一个适当有效的函数作为完成处理函数参数，还是会有作为替代的一个默认处理函数：
```javascript
var p = Promise.resolve(42);

p.then(
    // 假定的完成处理函数，如果省略或者传入任何非函数值
    // function(v) {
    //     return v;
    // }
    null,
    function rejected(err) {
        // 永远不会到这里
    }
)
```
默认的完成处理函数只是把接收到的任何传入值传递给下一个步骤而已。

`then(null, function(err) { .. })` 这个模式，只处理拒绝(如果有的话)，但又把完成值传递下去，有一个缩写形式的 API：`catch(function(err) { .. })`。

使链式流程控制可行的 Promise 固有特性：
- 调用 Promise 的 then(..) 会自动创建一个新的 Promise 从调用返回。
- 在完成或拒绝处理函数内部，如果返回一个值或抛出一个异常，新返回的(可链接的) Promise 就相应地决议。
- 如果完成或拒绝处理函数返回一个 Promise，它将会被展开，这样一来，不管它的决议值是什么，都会成为当前 then(..) 返回的链接 Promise 的决议值。

Promise 规范化了异步，并封装了时间相关值的状态，使得我们能够把它们以这种有用的方式链接到一起。

### 术语：决议 resolve、完成 fulfill 以及拒绝 reject
```javascript
var p = new Promise(function(X, Y) {
    // X() 用于完成
    // Y() 用于拒绝
})
```
第二个参数名称很容易决定，几乎所有的文献都将其命名 reject(..)，因为这就是它真实的(也是唯一的)工作。

但是，第一个参数就有一些模糊了，Promise 文献通常将其称为 resolve(..)，这个词显然与决议(resolution)有关，而决议在各种文献中是用来描述为 Promise 设定最终值/状态。Promise 决议表示完成或拒绝 Promise。

为什么不使用 fulfill(..) 来代替 resolve(..) 以求表达更准确呢？

Promise.resolve(..) 创建了一个决议为输入值的 Promise，Promise.reject(..) 创建了一个被拒绝的 Promise。

在 Promise.resolve(..) 中如果用于表达结果可能是完成也可能是拒绝的话，既没有歧义，而且也确实更准确：
```javascript
var rejectedTh = {
    then: function(resolved, rejected) {
        rejected("Oops");
    }
}
var rejectedPr = Promise.resolve(rejectedTh);
```
Promise.resolve(..) 会将传入的真正 Promise 直接返回，对传入的 thenable 则会展开，如果这个 thenable 展开得到的是一个拒绝状态，那么从 Promise.resolve(..) 返回的 Promise 实际上就是一个拒绝状态。

Promise(..) 构造器的第一个参数会展开 thenable 或真正的 Promise：
```javascript
var rejectedPr = new Promise(function(resolve, reject) {
    // 用一个被拒绝的 promise 完成这个 promise
    resolve(Promise.reject("Oops"));
})

rejectedPr.then(
    function fulfilled() {
        console.log('Here')
    },
    function rejected(err) {
        console.log(err);
    }
)

// Oops
```
因此，Promise(..) 构造器的第一个回调参数的恰当称谓是 resolve(..)。

注意⚠️：reject(..) 方法不会像 resolve(..) 一样进行展开，如果向 reject(..) 传入一个 Promise/thenable 值，它会把这个值原封不动地设置为拒绝理由，后续的拒绝处理函数接收到的是实际传递给 reject(..) 的 Promise/thenable，而不是其底层的立即值。

对于提供给 then(..) 的回调，可以使用 fulfilled(..) 和 rejected(..)，对于 then(..) 的第一个参数来说，毫无疑问，总是处理完成的情况。


## 错误处理
错误处理最自然的形式就是同步的 try..catch 结构，但是，它只能是同步的，无法用于异步代码模式：
```javascript
function foo() {
    setTimeout(function() {
        baz.bar();
    }, 0);
}

try {
    foo();
} catch(err) {
    console.log(err);
}

// Uncaught ReferenceError: baz is not defined
```
error-first 回调风格，传给 foo(..) 的回调函数保留第一个参数 err，用于在出错时接收到信号。但是多级 error-first 回调交织在一起，再加上无处不在的 if 检查语句，都不可避免地导致了回调地狱的风险。

Promise 使用了分离调用(split-callback)风格，一个回调用于完成情况，一个回调用于拒绝情况。
```javascript
var p = Promise.resolve(42);

p.then(
    function fulfilled(msg) {
        console.log(msg.toLowerCase());
    },
    function rejected(err) {
        console.log(err)
    }
)

// Promise {<rejected>: TypeError: msg.toLowerCase is not a function at fulfilled (<anonymous>:5:25)}
```

### 绝望的陷阱 pit of despair
pit \[pɪt] n.深洞; 深坑; 矿井;

despair \[dɪˈsper] n.绝望;

Promise 错误处理就是一个绝望的陷阱设计。默认情况下，它假定 Promise 状态吞掉所有的错误。如果忘记了查看这个状态，这个错误就会默默地在暗处凋零死掉。

为了避免丢失被忽略和抛弃的 Promise 错误，Promise 链的一个最佳实践是最后总以一个 catch(..) 结束。

但是，任何 Promise 链的最后一步，不管是什么，总是存在着未被查看的 Promise 中出现未捕获错误的可能性，尽管这种可能性越来越低。

### 处理未捕获的情况
Promise 应该添加一个 done(..) 函数，从本质上标识 Promise 链的结束。done(..) 不会创建和返回 Promise，所以传递给 done(..) 的回调不会报告一个并不存在的链接 Promise 的问题。

```javascript
var p = Promise.resolve(42);

p.then(function fulfilled(msg) {
    console.log(msg.toLowerCase());
}).done(null, handleErrors);
```
done(..) 拒绝处理函数内部的任何异常都会被作为一个全局未处理错误抛出。

浏览器可以追踪 Promise 对象，如果在它被垃圾回收的时候其中有拒绝，浏览器就能够确保这是一个真正的未捕获错误，进而可以确定应该将其报告到开发者终端。

但是，如果一个 Promise 未被垃圾回收，那么浏览器的垃圾回收嗅探就无法诊断一个被默默拒绝的 Promise。

### 成功的坑
默认情况下，Promise 在下一个任务或时间循环 tick 上(向开发者终端)报告所有拒绝，如果在这个时间点上该 Promise 还没有注册错误处理函数。

如果想要一个被拒绝的 Promise 在查看之前的某个时间段内保持被拒绝的状态，可以调用 defer()，这个函数优先级高于该 Promise 的自动错误报告。

如果一个 Promise 被拒绝的话，默认情况下会向开发者终端报告这个事实，而不是默认为沉默。可以选择隐式(在拒绝之前注册一个错误处理函数)或者显式(通过 defer())禁止这种报告。

默认情况下，所有的错误要么被处理要么被报告。因此，你要么注册一个处理函数要么特意选择退出，并表明把错误处理延迟到将来，这时候是在为特殊情况主动承担特殊的责任。


## Promise 模式
### Promise.all([..])
在异步序列(Promise 链)中，任意时刻都只能有一个异步任务正在进行。

门(gate)是这样一种机制，要等待两个或多个并行/并发的任务都完成才能继续。它们的完成顺序并不重要，但是必须都要完成，门才能打开并让控制流程继续。

Promise.all(\[..]) 需要一个数组参数，通常由 Promise 实例组成。从 Promise.all(\[..]) 调用返回的 promise 会收到一个完成消息，这是一个由所有传入 promise 的完成消息组成的数组，与指定的顺序一致(与完成的顺序无关)。

严格来说，传给 Promise.all(\[..]) 的数组中的值可以是 Promise、thenable、甚至是立即值。就本质而言，列表中的每个值都会通过 Promise.resolve(..) 过滤，以确保要等待的是一个真正的 Promise，所以立即值会被规范化为这个值构建的 Promise。如果数组是空的，主 Promise 就会立即完成。

从 Promise.all(\[..]) 返回的主 promise 在且仅在所有的成员 promise 都完成后才会完成。如果这些 promise 中有任何一个被拒绝的话，主 promise 就会立即被拒绝，并丢弃来自其他所有 promise 的全部结果。

### Promise.race(\[..])
门闩：响应第一个跨过终点线的 promise，而抛弃其他 promise。在 Promise 中称为竞态。

Promise.race(\[..]) 接受单个数组参数，这个数组由一个或多个 promise、thenable 或立即值组成。立即值之间的竞争在实践中没有太大的意义，因为显然列表中的第一个会获胜。

一旦有任何一个 promise 决议为完成，Promise.race(\[..]) 就会完成；一旦有任何一个 Promise 决议为拒绝，它就会拒绝。

注意⚠️：一项竞赛需要至少一个参赛者。如果传入了一个空数组，主 promise 就永远不会决议，而不是立即决议。因此，永远不要递送空数组。

### 并发迭代


## Promise API 概述
### new Promise(..) 构造器
### Promise.resolve(..) 和 Promise.reject(..)
### then(..) 和 catch(..)
### Promise.all([..]) 和 Promise.race([..])

## Promise 局限性
### 顺序错误处理
如果构建了一个没有错误处理函数的 Promise 链，链中任何地方的任何错误都会在链中一直传播下去，直到被查看(通过在某个步骤注册拒绝处理函数)。

### 单一值
根据定义，Promise 只能有一个完成值或一个拒绝理由。

可以构造一个值(对象或数组)封装来保持这样的多个信息。

ES6 提供了数组参数结构形式，符合了每个 Promise 一个值的理念，同时又将重复样板代码量保持在了最小！
```javascript
Promise.all([p1, p2])
.then(function([x, y]) {
    console.log(x, y);
})
```

### 单决议
Promise 最本质的一个特征：Promise 只能被决议一次(完成或拒绝)。

类似于事件和/或数据流的模式，可能多次发生。

### 惯性
现存代码和新代码的编程风格变化。

```javascript
// polyfill 安全的 guard 检查
if (!Promise.wrap) {
    Promise.wrap = function(fn) {
        return function() {
            var args = [].slice.call(arguments);
            return new Promise(function(resolve, reject) {
                fn.apply(null, args.concat(function(err, v) {
                    if (err) {
                        reject(err);
                    } else {
                        resolve(v);
                    }
                }))
            })
        }
    }
}
```
它接受一个函数，这个函数需要一个 error-first 风格的回调作为第一个参数，并返回一个新的函数。返回的函数自动创建一个 Promise 并返回，并替换回调，连接到 Promise 完成或拒绝。

产生  Promise 的函数可以看作是一个 Promise 工厂。

把需要回调的函数封装为支持 Promise 的函数，这个动作有时被称为“提升”或“Promise 工厂化”。

### 无法取消的 Promise
一旦创建了一个 Promise 并为其注册了完成和/或拒绝处理函数，如果出现某种情况使得这个任务悬而未决的话，没有办法从外部停止它的进程。

取消这个功能属于 Promise 之上的更高级的抽象。单独的一个 Promise 并不是一个真正的流程控制机制，相比之下，集合在一起的 Promise 构成的链，就是一个流程控制的表达，因此将取消定义在这个抽象层次上是合适的。

单独的 Promise 不应该可取消，但是取消一个可序列是合理的。

### Promise 性能
Promise 通常要比其他非 Promise、非可信任回调的等价系统稍微慢一点。

Promise 使所有一切都成为异步的了，即有一些立即(同步)完成的步骤仍然会延迟到任务的下一步，这意味着一个 Promise 任务序列可能比完全通过回调连接的同样的任务序列运行得稍慢一些。

几乎所有那些你可能认为 Promise 性能会慢到需要担心的情况，实际上都是通过绕开 Promise 可信任性和可组合性又花掉了它们带来的好处的反模式。

Promise 稍慢一些，但是作为交换，你得到的是大量内建的可信任性、对 Zalgo 的避免以及可组合性。


## 总结
Promise 解决了我们因只用回调的代码而备受困扰的控制反转的问题。

它并没有摒弃回调，只是把回调的安排转交给了一个位于我们和其他工具之间的可信任的中间机制。


## 参考
[1] Kyle Simpson. You Don't Know JS